apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "prometheus-prb"
  description: "Prueba de prometheus"
  annotations:
    github.com/project-slug: angeelsanchez/prometheus-prb
    backstage.io/techdocs-ref: dir:.
    prometheus.io/scrape: "true"             # Habilita la recolección de métricas de Prometheus
    prometheus.io/path: "/metrics"           # Ruta relativa al punto de enlace de métricas
    #prometheus.io/port: "9090"
    prometheus.io/alert: 'memUsage'
    #prometheus.io/alert: 'Excessive Memory Usage'
    prometheus.io/rule: go_gc_duration_seconds, http_requests_total
    #prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
    #grafana/dashboard-selector: "(tags @> 'my-service' || tags @> 'my-service-slo') && tags @> 'generated'"
    jenkins.io/job-full-name: job/backstage-1
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
